version: "3"

# Optional services - not for regular workshop like FOSS4G.
# start in background: docker-compose -f docker-compose-services.yml up -d
# stop:                docker-compose -f docker-compose-services.yml stop
services:

  pygeoapi:
    container_name: geopython-workshop-pygeoapi
    image: geopython/pygeoapi:latest
    ports:
      - 5000:80
    volumes:
      - ./services/pygeoapi-config.yml:/pygeoapi/local.config.yml:ro
      - ./jupyter/content/data:/jupyter/content/data:ro

  pycsw:
    container_name: geopython-workshop-pycsw
    image: geopython/pycsw:latest
    ports:
      - 8001:8000
    volumes:
      - ./jupyter/content/data:/jupyter/content/data:ro
      - ./services/pycsw-config.cfg:/etc/pycsw/pycsw.cfg:ro
