name: website ⚙️

on:
  push:
    paths:
    - 'web/docs/**'

jobs:
  build:
    name: Build and Deploy Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements 📦
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      - name: Deploy 📦
        run: cd web && mkdocs gh-deploy --force -m 'update website'
